language: cpp

compiler:
  - clang
  - gcc

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.5
  - if [ "$CXX" == "clang++" ]; then sudo apt-add-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'; fi
  - if [ "$CXX" == "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq --force-yes install clang-3.5; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; fi

  - sudo apt-get install -qq xorg-dev

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
  - make -j4
  - make test_path_tracer -j4
  - ./test_path_tracer
