language: cpp

os:
  - linux
  - osx

before_install:
  - git submodule update --init

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
  - make -j4
  - make test_path_tracer -j4
