language: cpp
os:
  - linux

compiler:
  #- clang
  - gcc

before_install:
  # g++6.1.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.6
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-6.1; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6.1"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.6; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.6"; fi

  - sudo apt-get install -qq xorg-dev
  - sudo apt-get install libboost-dev

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
  - make path_tracer_lib -j4
  - make path_tracer_test -j4
  - ./path_tracer_test
